version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

  test:
    docker:
      - image: cimg/ruby:2.7.2-node
      - image: circleci/postgres:9.5-alpine
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: RSpec
          command: |
            bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
